import { createClientFromRequest } from 'npm:@base44/sdk@0.7.1';
import { v4 as uuidv4 } from 'npm:uuid@9.0.0';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const body = await req.json();
    const { 
      serviceRequestId, 
      supplierOwnBookingId,
      notificationType = 'both', // 'email', 'whatsapp', 'both'
      autoGenerated = false,
      additionalPhone, // Telefone adicional para envio manual
      skipPassengerNotification = false // Flag para não enviar ao passageiro (apenas ao adicional)
    } = body;

    // Identificar qual ID foi passado (suporte a serviceRequestId genérico vindo do frontend)
    const idToSearch = serviceRequestId || supplierOwnBookingId;

    if (!idToSearch) {
      return Response.json({ 
        success: false, 
        error: 'ID da viagem é obrigatório' 
      }, { status: 400 });
    }

    let trip = null;
    let tripType = null; // 'service_request' | 'supplier_own_booking'

    // 1. Tentar buscar como ServiceRequest
    const serviceRequests = await base44.asServiceRole.entities.ServiceRequest.filter({ 
      id: idToSearch 
    });

    if (serviceRequests.length > 0) {
      trip = serviceRequests[0];
      tripType = 'service_request';
    } else {
      // 2. Se não encontrou, tentar como SupplierOwnBooking
      const ownBookings = await base44.asServiceRole.entities.SupplierOwnBooking.filter({
        id: idToSearch
      });

      if (ownBookings.length > 0) {
        trip = ownBookings[0];
        tripType = 'supplier_own_booking';
      }
    }

    if (!trip) {
      return Response.json({ 
        success: false, 
        error: 'Viagem não encontrada (ServiceRequest ou SupplierOwnBooking)' 
      }, { status: 404 });
    }

    // Verificar se já existe um link ativo para esta viagem
    const filterQuery = { status: 'active' };
    if (tripType === 'service_request') {
      filterQuery.service_request_id = trip.id;
    } else {
      filterQuery.supplier_own_booking_id = trip.id;
    }

    const existingTimelines = await base44.asServiceRole.entities.SharedTripTimeline.filter(filterQuery);

    let sharedTimeline;
    let isNewLink = false;

    if (existingTimelines.length > 0) {
      // Usar link existente
      sharedTimeline = existingTimelines[0];
    } else {
      // Criar novo link
      isNewLink = true;
      const token = uuidv4();
      
      // Obter usuário atual (se autenticado)
      let currentUser = null;
      try {
        currentUser = await base44.auth.me();
      } catch (error) {
        // Sem autenticação (pode ser automático)
      }

      const createPayload = {
        token: token,
        shared_by_user_id: currentUser?.id || null,
        first_shared_at: new Date().toISOString(),
        status: 'active',
        auto_generated: autoGenerated,
        shared_to_contacts: []
      };

      if (tripType === 'service_request') {
        createPayload.service_request_id = trip.id;
      } else {
        createPayload.supplier_own_booking_id = trip.id;
      }

      sharedTimeline = await base44.asServiceRole.entities.SharedTripTimeline.create(createPayload);
    }

    // Construir URL do link - usar BASE_URL do ambiente ou detectar automaticamente
    const baseUrl = Deno.env.get('BASE_URL') || `https://${req.headers.get('host')}`;
    // Ajuste: Removendo o hash (#) para compatibilidade com History API (BrowserRouter)
    // O frontend utiliza BrowserRouter, então a rota correta é /SharedTripTimeline?token=...
    const timelineUrl = `${baseUrl}/SharedTripTimeline?token=${sharedTimeline.token}`;

    console.log('[generateSharedTimelineLink] URL gerada:', timelineUrl);

    // Preparar lista de contatos para enviar
    const contactsToNotify = [];

    // Proteção: Verificar se o status da viagem já indica que o passageiro embarcou ou finalizou.
    // Se sim, NÃO enviar a notificação de "A Caminho" (que é o padrão desta função), pois seria confuso/duplicado.
    const currentStatus = trip.driver_trip_status || trip.driver_current_status;
    const advancedStatuses = ['passageiro_embarcou', 'a_caminho_destino', 'chegou_destino', 'finalizada', 'cancelada_motorista', 'no_show'];
    
    if (advancedStatuses.includes(currentStatus)) {
         console.log(`[generateSharedTimelineLink] Status avançado (${currentStatus}), pulando envio de notificação "A Caminho".`);
         return Response.json({
            success: true,
            timelineUrl,
            message: 'Link obtido, notificação ignorada pois a viagem já está em andamento/finalizada.'
         });
    }
    
    // Normalizar dados de contato (SupplierOwnBooking vs ServiceRequest)
    const passengerEmail = trip.passenger_email;
    const passengerPhone = trip.passenger_phone;
    const passengerName = trip.passenger_name;
    const tripNumber = trip.request_number || trip.booking_number; // ServiceRequest vs SupplierOwnBooking

    // Adicionar email do passageiro (se não for para pular)
    // ADICIONADO: Se a timeline foi gerada por "passageiro_embarcou" (verificado via autoGenerated ou contexto), talvez devêssemos pular?
    // Mas esta função não sabe o status.
    // Vamos confiar no flag skipPassengerNotification que quem chama deve passar.
    if (!skipPassengerNotification && passengerEmail && ['email', 'both'].includes(notificationType)) {
      contactsToNotify.push({
        type: 'email',
        value: passengerEmail,
        name: passengerName
      });
    }

    // Adicionar telefone do passageiro (se não for para pular)
    if (!skipPassengerNotification && passengerPhone && ['whatsapp', 'both'].includes(notificationType)) {
      contactsToNotify.push({
        type: 'whatsapp',
        value: passengerPhone,
        name: passengerName
      });
    }

    // Adicionar telefones de notificação extras da viagem (ServiceRequest.notification_phones)
    // Isso garante que os números cadastrados na viagem também recebam o link, sempre com dados atualizados
    if (!skipPassengerNotification && trip.notification_phones && Array.isArray(trip.notification_phones) && ['whatsapp', 'both'].includes(notificationType)) {
      for (const phone of trip.notification_phones) {
        if (phone && phone.trim().length > 5) { // Validação básica
           // Evitar duplicatas se o número já estiver na lista (ex: mesmo do passageiro)
           const alreadyAdded = contactsToNotify.some(c => c.value === phone);
           if (!alreadyAdded) {
             contactsToNotify.push({
               type: 'whatsapp',
               value: phone,
               name: 'Contato Adicional'
             });
           }
        }
      }
    }

    // Adicionar telefone adicional manual (se fornecido)
    if (additionalPhone) {
      contactsToNotify.push({
        type: 'whatsapp',
        value: additionalPhone,
        name: 'Contato Adicional'
      });
    }

    // Enviar notificações
    const sentContacts = [];
    let emailSent = false;
    let whatsappSent = false;
    let emailError = null;
    let whatsappError = null;

    for (const contact of contactsToNotify) {
      if (contact.type === 'email') {
        try {
          await base44.asServiceRole.integrations.Core.SendEmail({
            to: contact.value,
            subject: `🚗 Acompanhe sua viagem ${tripNumber} em tempo real`,
            body: `
              <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                <div style="background: linear-gradient(135deg, #2563eb 0%, #1e40af 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0;">
                  <h1 style="margin: 0; font-size: 28px;">🚗 Sua Viagem Está a Caminho!</h1>
                </div>
                
                <div style="background: white; padding: 30px; border: 1px solid #e5e7eb; border-top: none;">
                  <p style="font-size: 16px; color: #374151; margin-bottom: 20px;">
                    Olá <strong>${contact.name || 'passageiro'}</strong>,
                  </p>
                  
                  <p style="font-size: 16px; color: #374151; margin-bottom: 30px;">
                    Sua viagem <strong>${tripNumber}</strong> está em andamento! 
                    Acompanhe o status em tempo real através do link abaixo:
                  </p>
                  
                  <div style="background: #f3f4f6; padding: 20px; border-radius: 8px; margin-bottom: 30px;">
                    <h3 style="margin: 0 0 10px 0; color: #1f2937; font-size: 14px;">📍 ROTA</h3>
                    <p style="margin: 0; color: #4b5563; font-size: 14px;">
                      <strong>Origem:</strong> ${trip.origin}<br>
                      <strong>Destino:</strong> ${trip.destination || 'Não informado'}
                    </p>
                  </div>

                  ${trip.driver_name ? `
                    <div style="background: #ecfdf5; padding: 20px; border-radius: 8px; border-left: 4px solid #10b981; margin-bottom: 30px;">
                      <h3 style="margin: 0 0 10px 0; color: #065f46; font-size: 14px;">👤 SEU MOTORISTA</h3>
                      <p style="margin: 0; color: #047857; font-size: 14px;">
                        <strong>${trip.driver_name}</strong><br>
                        ${trip.driver_phone ? `📞 ${trip.driver_phone}<br>` : ''}
                        ${trip.vehicle_model ? `🚗 ${trip.vehicle_model}<br>` : ''}
                        ${trip.vehicle_plate ? `🚙 Placa: <strong>${trip.vehicle_plate}</strong>` : ''}
                      </p>
                    </div>
                  ` : ''}
                  
                  <div style="text-align: center; margin: 30px 0;">
                    <a href="${timelineUrl}" 
                       style="display: inline-block; background: linear-gradient(135deg, #2563eb 0%, #1e40af 100%); 
                              color: white; padding: 16px 40px; text-decoration: none; 
                              border-radius: 8px; font-weight: bold; font-size: 16px; box-shadow: 0 4px 6px rgba(37, 99, 235, 0.3);">
                      🔍 Acompanhar Viagem em Tempo Real
                    </a>
                  </div>
                  
                  <div style="background: #fffbeb; border: 1px solid #fbbf24; padding: 15px; border-radius: 8px; margin-top: 30px;">
                    <p style="margin: 0; font-size: 14px; color: #92400e;">
                      <strong>💡 Dica:</strong> Salve este link! Você pode acessá-lo a qualquer momento para ver atualizações em tempo real, 
                      incluindo quando o motorista estiver a caminho do destino com o tempo estimado de chegada.
                    </p>
                  </div>
                </div>
                
                <div style="background: #f9fafb; padding: 20px; text-align: center; border-radius: 0 0 10px 10px; border: 1px solid #e5e7eb; border-top: none;">
                  <p style="margin: 0; font-size: 12px; color: #6b7280;">
                    Esta é uma mensagem automática. Por favor, não responda a este e-mail.<br>
                    © ${new Date().getFullYear()} TransferOnline - Sistema de Gestão de Viagens
                  </p>
                </div>
              </div>
            `
          });
          
          emailSent = true;
          sentContacts.push({
            contact_type: 'email',
            contact_value: contact.value,
            sent_at: new Date().toISOString()
          });
        } catch (error) {
          console.error('[generateSharedTimelineLink] Erro ao enviar email:', error);
          emailError = error.message;
        }
      }

      if (contact.type === 'whatsapp') {
        try {
          // Construir a mensagem
          let message = `🚗 *Sua Viagem Está a Caminho!*\n\n`;
          message += `Olá *${contact.name || 'passageiro'}*,\n\n`;
          message += `Sua viagem *${tripNumber}* está em andamento!\n\n`;
          message += `📍 *ROTA*\n`;
          message += `🟢 Origem: ${trip.origin}\n`;
          message += `🔴 Destino: ${trip.destination || 'Não informado'}\n\n`;
          
          if (trip.driver_name) {
            message += `👤 *SEU MOTORISTA*\n`;
            message += `${trip.driver_name}\n`;
            if (trip.driver_phone) {
              message += `📞 ${trip.driver_phone}\n`;
            }
            if (trip.vehicle_model) {
              message += `🚗 ${trip.vehicle_model}\n`;
            }
            if (trip.vehicle_plate) {
              message += `🚙 *Placa: ${trip.vehicle_plate}*\n`;
            }
            message += `\n`;
          }
          
          message += `🔍 *Acompanhe a Time Line da Viagem:*\n`;
          message += `${timelineUrl}\n\n`;
          message += `💡 *Dica:* Salve este link! Você verá atualizações em tempo real, incluindo o tempo estimado de chegada quando o motorista estiver a caminho do destino.\n\n`;
          message += `_Esta é uma mensagem automática do TransferOnline_`;

          // Usar a função centralizada sendWhatsAppMessage para garantir compatibilidade (Z-API/Evolution)
          const response = await base44.functions.invoke('sendWhatsAppMessage', {
            to: contact.value,
            message: message
          });

          if (!response.data || !response.data.success) {
             throw new Error(response.data?.error || 'Erro desconhecido ao enviar WhatsApp via função central');
          }

          whatsappSent = true;
          sentContacts.push({
            contact_type: 'phone',
            contact_value: contact.value,
            sent_at: new Date().toISOString()
          });
        } catch (error) {
          console.error('[generateSharedTimelineLink] Erro ao enviar WhatsApp:', error);
          whatsappError = error.message;
        }
      }
    }

    // Atualizar registro com contatos notificados
    if (sentContacts.length > 0) {
      await base44.asServiceRole.entities.SharedTripTimeline.update(sharedTimeline.id, {
        shared_to_contacts: [
          ...(sharedTimeline.shared_to_contacts || []),
          ...sentContacts
        ]
      });
    }

    return Response.json({
      success: true,
      timelineUrl,
      isNewLink,
      emailSent,
      whatsappSent,
      emailError,
      whatsappError,
      message: isNewLink 
        ? 'Link de linha do tempo criado e enviado com sucesso!'
        : 'Link existente reenviado com sucesso!'
    });

  } catch (error) {
    console.error('[generateSharedTimelineLink] Erro:', error);
    return Response.json({
      success: false,
      error: error.message || 'Erro ao gerar link da linha do tempo'
    }, { status: 500 });
  }
});